title: Material-design-jp
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until baseurl
  Write an awesome description for your new site here. This will display on Google Search as well as footer.

baseurl: ""
url: /

markdown: kramdown
highlighter: rouge

plugins:
 - jekyll-seo-tag